### ISSUE TITLE
Compatibility with Status-4-Evar

### ISSUE THREAD

**Issue by tlgreg** [nightwing/smart-text#1]
Hi!

I would like to use your great addon with Status-4-Evar, which has an option to display status messages and links in the URLBar like in older Firefox 4 betas, but when I use smart-text those messages are replaced with an ellipsis or three dots.

I'm using:
- Firefox 4.0 released version
- smart text 4.2.4b4
- Status-4-Evar 2011.03.21.22

I'm gonna report the compatibility issue on Status-4-Evar's support topic too, when mozillazine is up again.

Thanks for your great addition to Firefox!

**Comment by nightwing** [comment]
hi!
to display status messages and links in the URLBar
you need to
  open smartText's options dialog (middle click on 3 dots, or from addon manager)
  and next to text 'status4evar integration' check button urlbarStatus
please tell if this works for you

**Comment by tlgreg** [comment]
Yeah, I forgot to mention, tried that, but not fixed it.

I have another addon which do something with the locationbar, or actually its dropdown: "Show Keywords 4", but I tried to disable it and nothing changed.

**Comment by nightwing** [comment]
worked with previous version :(
fix is very simple but should be done in status4evars code 
i'll write about it in Status-4-Evar's forum once mozillazine is up
thank you very much for report
