### ISSUE TITLE
conflict with the extension Mozilla Prospector Instant Preview + AwesomeBar HD

### ISSUE THREAD

**Issue by UaHummer** [nightwing/smart-text#2]
increases the navigation toolbar (the screenshot shows it - http://db.tt/EDuLds0) twice
also blocks the entry of characters in it...

**Comment by nightwing** [comment]
thank you for bug report, but i can't reproduce it :(

i've installed smart-text
and https://addons.mozilla.org/en-US/firefox/addon/prospector-instant-preview/
on new profile
but everything worked normally

can you give a little bit more info,
maybe you have some other extension installed as well?

**Comment by UaHummer** [comment]
my mistake - should be AwesomeBar HD 14 + Instant Preview = bug

**Comment by nightwing** [comment]
sorry for such a late response. 
unfortunately the way AwesomeBar HD changes urlbar doesn't allow other addons modify urlbar in the same time
