### ISSUE TITLE
Breaks 'Switch to Tab'

### ISSUE THREAD

**Issue by tyaremco** [nightwing/smart-text#3]
Selecting a 'Switch to tab' url from the url bar search list will just load the tab again, and not change focus to the existing tab.

**Comment by nightwing** [comment]
Hi

sorry for late response

[here's](https://github.com/downloads/nightwing/smart-text/smart@text-a.am.switch-to-tab.xpi) a version that should work with switch to tab
i am planning to make "disable switch to tab" option
but don't know when i'll have time for it (maybe a month + 3 weeks for AMO to review)

**Comment by tyaremco** [comment]
Thank you; I appreciate it!
